development:
  FACEBOOK_APP_ID: 123456789
  site_domain: battle.ru
  site_port: 3000
  consider_ip: "false"
test:
 FACEBOOK_APP_ID: 987654321
production:
  FACEBOOK_APP_ID: 147258369
  consider_ip: "true"